In [ ]:
# Task 1 : Text Cleaning Pipeline

In [ ]:
!pip install contractions nltk -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.1/345.1 kB 8.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 5.6 MB/s eta 0:00:00

In [ ]:
import re
import contractions
import nltk
import pandas as pd

from nltk.corpus import stopwords

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
review = """I'm really HAPPY about this product!!! It's amazing & I don't
think I've ever used something this good. @product #awesome"""

print("Original Review:")
print(review)

Original Review:
I'm really HAPPY about this product!!! It's amazing & I don't
think I've ever used something this good. @product #awesome

In [ ]:
stop_words = set(stopwords.words('english'))

def clean_text(text):

    # Step 1: Count words before preprocessing
    words_before = len(text.split())

    # Step 2: Expand contractions
    # Example:
    # don't -> do not
    # can't -> cannot
    # I'm -> I am
    # it's -> it is
    text = contractions.fix(text)

    # Step 3: Case Folding
    text = text.lower()

    # Step 4: Remove special characters
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)

    # Step 5: Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    # Step 6: Remove stopwords
    words = text.split()

    cleaned_words = [
        word for word in words
        if word not in stop_words
    ]

    cleaned_text = ' '.join(cleaned_words)

    # Step 7: Count words after preprocessing
    words_after = len(cleaned_text.split())

    return cleaned_text, words_before, words_after

In [ ]:
cleaned_review, before_count, after_count = clean_text(review)

print("Original Text:")
print(review)

Original Text:
I'm really HAPPY about this product!!! It's amazing & I don't
think I've ever used something this good. @product #awesome

In [ ]:
print("\nCleaned Text:")
print(cleaned_review)

Cleaned Text:
really happy product amazing think ever used something good product awesome

In [ ]:
print("\nNumber of words before preprocessing:", before_count)
print("Number of words after preprocessing:", after_count)

Number of words before preprocessing: 20
Number of words after preprocessing: 11

In [ ]:
result = pd.DataFrame({
    "Original Text": [review],
    "Cleaned Text": [cleaned_review],
    "Words Before": [before_count],
    "Words After": [after_count]
})

result

,Original Text,Cleaned Text,Words Before,Words After
0,I'm really HAPPY about this product!!! It's am...,really happy product amazing think ever used s...,20,11

In [ ]:
# Task 2: Social Media Text Cleaning

In [ ]:
ltk.download('stopwords')

stop_words = set(stopwords.words('english'))

["OMG!!! I can't believe this 😍 @user #Amazing",
 "This movie wasn't good... I don't recommend it!!!",
 "I'm LOVING this product!!! It's sooo good 😍"]

In [ ]:
def clean_social_media_text(text):

    # 1. Expand contractions
    # can't -> cannot
    # wasn't -> was not
    # I'm -> I am
    text = contractions.fix(text)

    # 2. Case folding
    text = text.lower()

    # 3. Remove mentions
    # Example: @user
    text = re.sub(r'@\w+', '', text)

    # 4. Remove hashtags
    # Example: #Amazing
    text = re.sub(r'#\w+', '', text)

    # 5. Remove special characters, emojis and punctuation
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)

    # 6. Remove unnecessary extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    # 7. Remove stopwords
    words = text.split()

    cleaned_words = [
        word for word in words
        if word not in stop_words
    ]

    cleaned_text = ' '.join(cleaned_words)

    return cleaned_text

In [ ]:
cleaned_comments = []

for comment in comments:
    cleaned = clean_social_media_text(comment)
    cleaned_comments.append(cleaned)

cleaned_comments

['omg cannot believe', 'movie good recommend', 'loving product sooo good']

In [ ]:
result = pd.DataFrame({
    "Original Comment": comments,
    "Cleaned Comment": cleaned_comments
})

result

                                    Original Comment           Cleaned Comment
0       OMG!!! I can't believe this 😍 @user #Amazing        omg cannot believe
1  This movie wasn't good... I don't recommend it!!!      movie good recommend
2        I'm LOVING this product!!! It's sooo good 😍  loving product sooo good

In [ ]:
# Task 3: Customer Review Preprocessing

In [ ]:
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
sample_reviews = [
    "I'm really HAPPY with this product!!! It's amazing and works perfectly.",
    "I don't like this product. It's very poor quality.",
    "This is the BEST product I've ever purchased!!!",
    "The delivery wasn't fast and the package was damaged.",
    "I'm satisfied with the product and its quality.",
    "It's amazing!!! I can't believe how good this product is.",
    "I won't recommend this product because the quality is bad.",
    "The product arrived on time and works perfectly.",
    "I'm not happy with the customer service.",
    "This product is affordable, useful, and very good.",
    "The quality is excellent and I'm very satisfied.",
    "I can't complain about the delivery. It was very fast.",
    "It's not worth the money. I don't recommend buying it.",
    "Amazing quality and excellent service!!!",
    "The product wasn't what I expected.",
    "I'm loving this product. It's easy to use.",
    "The delivery was late but the product is good.",
    "I don't think this product is worth buying.",
    "Excellent product with great quality.",
    "The product works well and I'm happy with my purchase."
]

In [ ]:
# Create 100 reviews by randomly selecting from sample reviews
random.seed(42)

reviews = [
    random.choice(sample_reviews)
    for _ in range(100)
]

df = pd.DataFrame({
    "review": reviews
})

df.head()

                                              review
0  The delivery wasn't fast and the package was d...
1  I'm really HAPPY with this product!!! It's ama...
2           I'm not happy with the customer service.
3   The product arrived on time and works perfectly.
4   The product arrived on time and works perfectly.

In [ ]:
print("Total number of reviews:", len(df))

Total number of reviews: 100

In [ ]:
def clean_review(text):

    # 1. Expand contractions
    # don't -> do not
    # can't -> cannot
    # I'm -> I am
    text = contractions.fix(text)

    # 2. Convert to lowercase
    text = text.lower()

    # 3. Remove special characters
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)

    # 4. Remove unnecessary whitespace
    text = re.sub(r'\s+', ' ', text).strip()

    # 5. Remove stopwords
    words = text.split()

    cleaned_words = [
        word for word in words
        if word not in stop_words
    ]

    cleaned_text = ' '.join(cleaned_words)

    return cleaned_text

In [ ]:
df["cleaned_review"] = df["review"].apply(clean_review)

df.head()

,review,cleaned_review
0,The delivery wasn't fast and the package was d...,delivery fast package damaged
1,I'm really HAPPY with this product!!! It's ama...,really happy product amazing works perfectly
2,I'm not happy with the customer service.,happy customer service
3,The product arrived on time and works perfectly.,product arrived time works perfectly
4,The product arrived on time and works perfectly.,product arrived time works perfectly

In [ ]:
df[["review", "cleaned_review"]].head(10)

,review,cleaned_review
0,The delivery wasn't fast and the package was d...,delivery fast package damaged
1,I'm really HAPPY with this product!!! It's ama...,really happy product amazing works perfectly
2,I'm not happy with the customer service.,happy customer service
3,The product arrived on time and works perfectly.,product arrived time works perfectly
4,The product arrived on time and works perfectly.,product arrived time works perfectly
5,I'm satisfied with the product and its quality.,satisfied product quality
6,The delivery wasn't fast and the package was d...,delivery fast package damaged
7,I don't think this product is worth buying.,think product worth buying
8,This is the BEST product I've ever purchased!!!,best product ever purchased
9,Excellent product with great quality.,excellent product great quality

In [ ]:
df["words_before"] = df["review"].apply(
    lambda x: len(x.split())
)

df.head()

,review,cleaned_review,words_before
0,The delivery wasn't fast and the package was d...,delivery fast package damaged,9
1,I'm really HAPPY with this product!!! It's ama...,really happy product amazing works perfectly,11
2,I'm not happy with the customer service.,happy customer service,7
3,The product arrived on time and works perfectly.,product arrived time works perfectly,8
4,The product arrived on time and works perfectly.,product arrived time works perfectly,8

In [ ]:
df["words_after"] = df["cleaned_review"].apply(
    lambda x: len(x.split())
)

df.head()

,review,cleaned_review,words_before,words_after
0,The delivery wasn't fast and the package was d...,delivery fast package damaged,9,4
1,I'm really HAPPY with this product!!! It's ama...,really happy product amazing works perfectly,11,6
2,I'm not happy with the customer service.,happy customer service,7,3
3,The product arrived on time and works perfectly.,product arrived time works perfectly,8,5
4,The product arrived on time and works perfectly.,product arrived time works perfectly,8,5

In [ ]:
average_before = df["words_before"].mean()
average_after = df["words_after"].mean()

In [ ]:

print("Average words before cleaning:", round(average_before, 2))
print("Average words after cleaning :", round(average_after, 2))

Average words before cleaning: 8.38
Average words after cleaning : 3.97

In [ ]:
all_words = " ".join(
    df["cleaned_review"]
).split()

word_frequency = Counter(all_words)

top_10_words = word_frequency.most_common(10)

print("10 Most Frequent Words:")

for word, count in top_10_words:
    print(word, ":", count)

10 Most Frequent Words:
product : 65
quality : 28
happy : 17
works : 17
delivery : 13
perfectly : 13
worth : 13
buying : 13
recommend : 13
fast : 12

In [ ]:
top_words_df = pd.DataFrame(
    top_10_words,
    columns=["Word", "Frequency"]
)

top_words_df

        Word  Frequency
0    product         65
1    quality         28
2      happy         17
3      works         17
4   delivery         13
5  perfectly         13
6      worth         13
7     buying         13
8  recommend         13
9       fast         12

In [ ]:
# Task 4: News Article Text Cleaning

In [ ]:
from collections import Counter

In [ ]:
news_articles = [
    "The government announced a new policy today!!! It's expected to improve economic growth.",
    "Scientists can't confirm the results yet, but the research looks promising.",
    "The stock market wasn't stable during today's trading session.",
    "A new technology company has launched an innovative AI product.",
    "The weather department says it won't rain heavily this week.",
    "I'm sure the new education policy will help students across the country.",
    "The central bank announced changes in interest rates on Monday.",
    "Health officials don't expect a major increase in seasonal infections.",
    "The country's football team won an important international match.",
    "Researchers have developed a new method for renewable energy generation.",
    "The transport department has announced new safety regulations.",
    "The company isn't planning to reduce its workforce this year.",
    "Global markets reacted positively after the latest economic report.",
    "The new smartphone has several advanced features and improved battery life.",
    "Officials can't provide additional details about the investigation.",
    "The city has introduced electric buses to reduce air pollution.",
    "Experts believe artificial intelligence will transform many industries.",
    "The university announced a new scholarship program for students.",
    "The airline won't cancel its scheduled international flights.",
    "A new environmental project aims to protect forests and wildlife."
]

df = pd.DataFrame({
    "article": news_articles
})

df

                                              article
0   The government announced a new policy today!!!...
1   Scientists can't confirm the results yet, but ...
2   The stock market wasn't stable during today's ...
3   A new technology company has launched an innov...
4   The weather department says it won't rain heav...
5   I'm sure the new education policy will help st...
6   The central bank announced changes in interest...
7   Health officials don't expect a major increase...
8   The country's football team won an important i...
9   Researchers have developed a new method for re...
10  The transport department has announced new saf...
11  The company isn't planning to reduce its workf...
12  Global markets reacted positively after the la...
13  The new smartphone has several advanced featur...
14  Officials can't provide additional details abo...
15  The city has introduced electric buses to redu...
16  Experts believe artificial intelligence will t...
17  The university announced a new scholarship pro...
18  The airline won't cancel its scheduled interna...
19  A new environmental project aims to protect fo...

In [ ]:
def clean_news_text(text):

    # 1. Handle contractions
    # can't -> cannot
    # won't -> will not
    # isn't -> is not
    text = contractions.fix(text)

    # 2. Case folding
    text = text.lower()

    # 3. Remove special characters
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)

    # Remove unnecessary spaces
    text = re.sub(r'\s+', ' ', text).strip()

    # 4. Remove stopwords
    words = text.split()

    cleaned_words = [
        word for word in words
        if word not in stop_words
    ]

    cleaned_text = ' '.join(cleaned_words)

    return cleaned_text

In [ ]:
df["cleaned_article"] = df["article"].apply(clean_news_text)

df

,article,cleaned_article
0,The government announced a new policy today!!!...,government announced new policy today expected...
1,"Scientists can't confirm the results yet, but ...",scientists cannot confirm results yet research...
2,The stock market wasn't stable during today's ...,stock market stable today trading session
3,A new technology company has launched an innov...,new technology company launched innovative ai ...
4,The weather department says it won't rain heav...,weather department says rain heavily week
5,I'm sure the new education policy will help st...,sure new education policy help students across...
6,The central bank announced changes in interest...,central bank announced changes interest rates ...
7,Health officials don't expect a major increase...,health officials expect major increase seasona...
8,The country's football team won an important i...,country football team important international ...
9,Researchers have developed a new method for re...,researchers developed new method renewable ene...
10,The transport department has announced new saf...,transport department announced new safety regu...
11,The company isn't planning to reduce its workf...,company planning reduce workforce year
12,Global markets reacted positively after the la...,global markets reacted positively latest econo...
13,The new smartphone has several advanced featur...,new smartphone several advanced features impro...
14,Officials can't provide additional details abo...,officials cannot provide additional details in...
15,The city has introduced electric buses to redu...,city introduced electric buses reduce air poll...
16,Experts believe artificial intelligence will t...,experts believe artificial intelligence transf...
17,The university announced a new scholarship pro...,university announced new scholarship program s...
18,The airline won't cancel its scheduled interna...,airline cancel scheduled international flights
19,A new environmental project aims to protect fo...,new environmental project aims protect forests...

In [ ]:
display(
    df[
        ["article", "cleaned_article"]
    ]
)

,article,cleaned_article
0,The government announced a new policy today!!!...,government announced new policy today expected...
1,"Scientists can't confirm the results yet, but ...",scientists cannot confirm results yet research...
2,The stock market wasn't stable during today's ...,stock market stable today trading session
3,A new technology company has launched an innov...,new technology company launched innovative ai ...
4,The weather department says it won't rain heav...,weather department says rain heavily week
5,I'm sure the new education policy will help st...,sure new education policy help students across...
6,The central bank announced changes in interest...,central bank announced changes interest rates ...
7,Health officials don't expect a major increase...,health officials expect major increase seasona...
8,The country's football team won an important i...,country football team important international ...
9,Researchers have developed a new method for re...,researchers developed new method renewable ene...
10,The transport department has announced new saf...,transport department announced new safety regu...
11,The company isn't planning to reduce its workf...,company planning reduce workforce year
12,Global markets reacted positively after the la...,global markets reacted positively latest econo...
13,The new smartphone has several advanced featur...,new smartphone several advanced features impro...
14,Officials can't provide additional details abo...,officials cannot provide additional details in...
15,The city has introduced electric buses to redu...,city introduced electric buses reduce air poll...
16,Experts believe artificial intelligence will t...,experts believe artificial intelligence transf...
17,The university announced a new scholarship pro...,university announced new scholarship program s...
18,The airline won't cancel its scheduled interna...,airline cancel scheduled international flights
19,A new environmental project aims to protect fo...,new environmental project aims protect forests...

In [ ]:
print("=" * 70)
print("NEWS ARTICLE TEXT CLEANING")
print("=" * 70)

print("\nTotal News Articles:", len(df))

print("\nOriginal and Cleaned Articles:\n")

display(
    df[
        ["article", "cleaned_article"]
    ]
)

======================================================================
NEWS ARTICLE TEXT CLEANING
======================================================================

Total News Articles: 20

Original and Cleaned Articles:

,article,cleaned_article
0,The government announced a new policy today!!!...,government announced new policy today expected...
1,"Scientists can't confirm the results yet, but ...",scientists cannot confirm results yet research...
2,The stock market wasn't stable during today's ...,stock market stable today trading session
3,A new technology company has launched an innov...,new technology company launched innovative ai ...
4,The weather department says it won't rain heav...,weather department says rain heavily week
5,I'm sure the new education policy will help st...,sure new education policy help students across...
6,The central bank announced changes in interest...,central bank announced changes interest rates ...
7,Health officials don't expect a major increase...,health officials expect major increase seasona...
8,The country's football team won an important i...,country football team important international ...
9,Researchers have developed a new method for re...,researchers developed new method renewable ene...
10,The transport department has announced new saf...,transport department announced new safety regu...
11,The company isn't planning to reduce its workf...,company planning reduce workforce year
12,Global markets reacted positively after the la...,global markets reacted positively latest econo...
13,The new smartphone has several advanced featur...,new smartphone several advanced features impro...
14,Officials can't provide additional details abo...,officials cannot provide additional details in...
15,The city has introduced electric buses to redu...,city introduced electric buses reduce air poll...
16,Experts believe artificial intelligence will t...,experts believe artificial intelligence transf...
17,The university announced a new scholarship pro...,university announced new scholarship program s...
18,The airline won't cancel its scheduled interna...,airline cancel scheduled international flights
19,A new environmental project aims to protect fo...,new environmental project aims protect forests...

In [39]:
df["words_before"] = df["article"].apply(
    lambda x: len(x.split())
)

total_words_before = df["words_before"].sum()

print("Total words before preprocessing:", total_words_before)

Total words before preprocessing: 195

In [40]:
df["words_after"] = df["cleaned_article"].apply(
    lambda x: len(x.split())
)

total_words_after = df["words_after"].sum()

print("Total words after preprocessing:", total_words_after)

Total words after preprocessing: 135

In [41]:
from collections import Counter

all_cleaned_words = " ".join(
    df["cleaned_article"]
).split()

word_frequency = Counter(all_cleaned_words)

top_10_words = word_frequency.most_common(10)

print("10 Most Frequent Words:")

for word, count in top_10_words:
    print(word, ":", count)

10 Most Frequent Words:
new : 8
announced : 4
policy : 2
today : 2
economic : 2
cannot : 2
company : 2
department : 2
students : 2
country : 2

In [42]:
all_original_text = " ".join(df["article"]).lower()

# Remove special characters
all_original_text = re.sub(
    r'[^a-zA-Z\s]',
    ' ',
    all_original_text
)

words = all_original_text.split()

stopword_list = [
    word for word in words
    if word in stop_words
]

stopword_frequency = Counter(stopword_list)

top_stopwords = stopword_frequency.most_common(10)

print("Most Frequent Stopwords:")

for word, count in top_stopwords:
    print(word, ":", count)

Most Frequent Stopwords:
the : 17
t : 7
a : 6
to : 4
has : 4
s : 3
won : 3
it : 2
can : 2
an : 2

In [43]:
words_removed = total_words_before - total_words_after

reduction_percentage = (
    words_removed / total_words_before
) * 100

print("Words Before :", total_words_before)
print("Words After  :", total_words_after)
print("Words Removed:", words_removed)

print(
    "Text Size Reduction:",
    round(reduction_percentage, 2),
    "%"
)

Words Before : 195
Words After  : 135
Words Removed: 60
Text Size Reduction: 30.77 %

In [ ]:
1.How many words were present before preprocessing?

The total number of words present in the original/raw text before performing any text-cleaning operations.

Formula:Words Before=Total number of words in original text

Python:words_before = len(original_text.split())

Example: If the original text contains 200 words:

Words Before=200

In [ ]:
2.How many words remained after preprocessing?

The total number of words remaining after removing stopwords, special characters, punctuation, and other unnecessary text.
Formula:Words After=Total number of words in cleaned text
Python:words_after = len(cleaned_text.split())
Example: If 120 words remain:
Words After

In [ ]:
3.Which 10 words occur most frequently?
The 10 words that occur the highest number of times in the cleaned text are called the top 10 most frequent words.

Formula:Frequency(w)=Number of times word w occurs

In [ ]:
4.Which stopwords appeared most frequently?
Stopwords are commonly occurring words that usually carry little meaning for text analysis.

Examples:the, is, a, an, and, of, to, in, was, this
The most frequent stopwords are the stopwords that appeared the greatest number of times in the original text.
Formula:Stopword Frequency(s)=Number of occurrences of stopword s

In [ ]:
5.How much did the text size reduce after preprocessing?

Text-size reduction tells us how much text was removed during preprocessing.

Formula for words removed
Words Removed=Words Before−Words After

Percentage reduction formula ⭐
Reduction %=Words Before/Words Before−Words After×100

Example

Suppose:Words Before=200, Words After=120

Step 1 — Find words removed:200−120=80

Step 2 — Find percentage: 200/80 ×100 =0.4×100 40%

Therefore, 80 words were removed and the text size was reduced by 40%.